language: scala
scala:
   - 2.10.2
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - npm install grunt

script: npm install && grunt && sbt ++$TRAVIS_SCALA_VERSION test
